name = "worker"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "./dist/index.mjs"

[build]
command = "npm install && npm test && npm run build"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "CounterTs"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["CounterTs"]
